apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
    app.kubernetes.io/name: {{ template "fullname" . }}
    mainProcess: ${BW_MAIN_PROCESS}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: http
{{- if .Values.bwce.monitoring.enabled }}
  - port: 9095
    targetPort: 9095
    protocol: TCP
    name: prom
{{- end }}
  selector:
    app.kubernetes.io/name: {{ template "fullname" . }}
