
{{- if or (eq .Values.service.enabled true) (eq  .Values.bwce.monitoring.enabled true) }}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/name: {{ template "fullname" . }}
    meta.helm.sh/chart:  "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.bwce.monitoring.enabled }}
    mainProcess: {{ .Values.bwce.monitoring.mainProcess}}
    {{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- if .Values.service.enabled }}
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: http
{{- end }}
{{- if .Values.bwce.monitoring.enabled }}
  - port: 9095
    targetPort: 9095
    protocol: TCP
    name: prom
{{- end }}
  selector:
    app.kubernetes.io/name: {{ template "fullname" . }}
{{- end }}
